"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Search,Settings2,ChevronRight,CalendarDays,Newspaper,Trophy,Home as HomeIcon,Radio,ExternalLink} from "lucide-react";
import {defaultFavoriteTeamIds,defaultLeaguePrefs,defaultNewsSources,events,stories,teamCatalog} from "@/data/demo";

const KEY="homefield-preferences-v1";
const API_NAMES:Record<string,string>={"stl-cardinals":"St. Louis Cardinals","stl-blues":"St. Louis Blues","indiana-football":"Indiana Hoosiers","indiana-basketball":"Indiana Hoosiers","slu-basketball":"Saint Louis Billikens","stl-city":"St. Louis City SC","man-utd":"Manchester United"};
const KNOWN_BADGES:Record<string,string>={
 "stl-cardinals":"https://a.espncdn.com/i/teamlogos/mlb/500/stl.png",
 "stl-blues":"https://a.espncdn.com/i/teamlogos/nhl/500/stl.png",
 "indiana-football":"https://a.espncdn.com/i/teamlogos/ncaa/500/84.png",
 "indiana-basketball":"https://a.espncdn.com/i/teamlogos/ncaa/500/84.png",
 "slu-basketball":"https://a.espncdn.com/i/teamlogos/ncaa/500/139.png",
 "stl-city":"https://a.espncdn.com/i/teamlogos/soccer/500/21812.png",
 "man-utd":"https://a.espncdn.com/i/teamlogos/soccer/500/360.png"
};
type LiveCard={teamId:string;title:string;detail:string;status?:string;eventId?:string;isLiveData:boolean;badge?:string;source?:string};
type NewsStory={id:string;headline:string;summary:string;source:string;league:string;url:string;image?:string|null;published?:string|null;favoriteTeamIds?:string[];personalized?:boolean};
function formatEventDetail(event:any){
 const dt=event?.dateTime?new Date(event.dateTime):null;
 const valid=dt&&!Number.isNaN(dt.getTime());
 const date=valid?dt.toLocaleDateString(undefined,{month:"short",day:"numeric"}):"Date TBD";
 const time=valid?dt.toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"}):"Time TBD";
 return [date,time,event?.venue].filter(Boolean).join(" · ")
}
function storyAge(value?:string|null){if(!value)return "Latest";const ms=Date.now()-new Date(value).getTime();if(!Number.isFinite(ms))return "Latest";const h=Math.max(0,Math.floor(ms/3600000));if(h<1)return "Just now";if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`}

export default function HomeField(){
 const [favoriteIds,setFavoriteIds]=useState(defaultFavoriteTeamIds);const [settings,setSettings]=useState(false);const [liveCards,setLiveCards]=useState<LiveCard[]>([]);const [gamesLoading,setGamesLoading]=useState(true);const [newsCards,setNewsCards]=useState<NewsStory[]>([]);const [newsLoading,setNewsLoading]=useState(true);
 useEffect(()=>{try{const r=localStorage.getItem(KEY);if(r)setFavoriteIds(JSON.parse(r).favoriteTeamIds||defaultFavoriteTeamIds)}catch{}},[]);
 const teams=useMemo(()=>favoriteIds.map(id=>teamCatalog.find(t=>t.id===id)).filter(Boolean) as typeof teamCatalog,[favoriteIds]);
 useEffect(()=>{let cancelled=false;async function load(){setGamesLoading(true);const results=await Promise.all(teams.map(async team=>{try{const res=await fetch(`/api/sports/team?key=${encodeURIComponent(team.id)}&name=${encodeURIComponent(API_NAMES[team.id]||team.name)}`);if(!res.ok)throw new Error("sports feed unavailable");const data=await res.json();const badge=KNOWN_BADGES[team.id]||data?.team?.badge;if(data?.nextEvent)return {teamId:team.id,title:data.nextEvent.name||team.name,detail:formatEventDetail(data.nextEvent),status:data.nextEvent.status||"NEXT",eventId:data.nextEvent.id,isLiveData:true,badge,source:data.source} satisfies LiveCard;if(data?.team)return {teamId:team.id,title:team.name,detail:"Schedule unavailable",status:"TEAM",isLiveData:true,badge,source:data.source} satisfies LiveCard}catch{}const fallback=events.find(e=>e.teamId===team.id);return fallback?{teamId:team.id,title:fallback.title,detail:fallback.detail,status:fallback.status,isLiveData:false,badge:KNOWN_BADGES[team.id]} satisfies LiveCard:null}));if(!cancelled){setLiveCards(results.filter(Boolean) as LiveCard[]);setGamesLoading(false)}}if(teams.length)load();else{setLiveCards([]);setGamesLoading(false)}return()=>{cancelled=true}},[teams]);
 useEffect(()=>{let cancelled=false;async function loadNews(){setNewsLoading(true);try{const res=await fetch(`/api/news?teams=${encodeURIComponent(favoriteIds.join(","))}`);if(!res.ok)throw new Error("news feed unavailable");const data=await res.json();if(!cancelled)setNewsCards((data?.stories||[]).slice(0,6))}catch{if(!cancelled)setNewsCards([])}finally{if(!cancelled)setNewsLoading(false)}}loadNews();return()=>{cancelled=true}},[favoriteIds]);
 const badgeByTeam=useMemo(()=>Object.fromEntries(liveCards.filter(x=>x.badge).map(x=>[x.teamId,x.badge])),[liveCards]);
 const toggle=(id:string)=>{const next=favoriteIds.includes(id)?favoriteIds.filter(x=>x!==id):[...favoriteIds,id];setFavoriteIds(next);try{const existing=JSON.parse(localStorage.getItem(KEY)||"{}");localStorage.setItem(KEY,JSON.stringify({...existing,favoriteTeamIds:next,leagues:existing.leagues||defaultLeaguePrefs,sources:existing.sources||defaultNewsSources}))}catch{localStorage.setItem(KEY,JSON.stringify({favoriteTeamIds:next,leagues:defaultLeaguePrefs,sources:defaultNewsSources}))}};
 return <main className="homeShell"><header className="homeHeader"><div><div className="brand">HOMEFIELD</div><small>YOUR TEAMS. FIRST.</small></div><div className="headerActions"><Link href="/search" className="iconBtn" aria-label="Search HomeField"><Search size={19}/></Link><button className="iconBtn" aria-label="Personalize HomeField" onClick={()=>setSettings(!settings)}><Settings2 size={19}/></button></div></header>
 {settings&&<section className="settingsPanel"><div className="sectionHead"><div><span className="eyebrow">PERSONALIZE</span><h2>Favorite teams</h2></div></div><div className="settingsTeams">{teamCatalog.map(t=><button key={t.id} className={favoriteIds.includes(t.id)?"settingsTeam active":"settingsTeam"} onClick={()=>toggle(t.id)}>{t.short} · {t.name}</button>)}</div><p>News priority: ESPN first, Bleacher Report second. Paid-only articles such as ESPN+ are excluded.</p></section>}
 <section className="heroWelcome"><span className="eyebrow">GOOD EVENING</span><h1>Your sports world,<br/>built around you.</h1><p>Favorite teams first. Followed leagues next. Big stories everywhere else.</p></section>
 <section className="homeSection"><div className="sectionHead"><div><span className="eyebrow">MY TEAMS</span><h2>HomeField</h2></div></div><div className="teamRail">{teams.map(t=>{const badge=KNOWN_BADGES[t.id]||badgeByTeam[t.id];return <Link href={`/team/${t.id}`} className="teamTile brandedTeamTile" style={{background:`radial-gradient(circle at 90% 0%,${t.primary}30,transparent 45%),#12171e`}} key={t.id}>{badge?<TeamBadge src={badge} label={t.short}/>:<div className="teamLogo" style={{background:`linear-gradient(145deg,${t.primary},${t.secondary})`}}>{t.short}</div>}<strong>{t.name}</strong><small>{t.league}</small></Link>})}</div></section>
 <section className="homeSection"><div className="sectionHead"><div><span className="eyebrow">LIVE & NEXT UP</span><h2>Your games</h2></div><Link href="/scores" className="backLink">All scores <ChevronRight size={15}/></Link></div>{gamesLoading?<div className="empty">Loading current schedules…</div>:<div className="gameGrid">{liveCards.map((g,i)=><Link href={g.isLiveData?`/team/${g.teamId}`:`/game/game-${Math.max(1,events.findIndex(e=>e.teamId===g.teamId)+1)}`} className="gameCard homeGameCard" key={`${g.teamId}-${g.eventId||i}`}>{g.badge?<TeamBadge src={g.badge} label={teamCatalog.find(t=>t.id===g.teamId)?.short||"HF"} small/>:g.isLiveData?<Radio/>:<CalendarDays/>}<div><span className="gameStatus">{g.status||"NEXT"}</span><strong>{g.title}</strong><small>{g.detail}</small>{g.isLiveData&&<small>{g.source||"Live sports feed"}</small>}</div><ChevronRight/></Link>)}</div>}</section>
 <section className="homeSection"><div className="sectionHead"><div><span className="eyebrow">TOP STORIES FOR YOU</span><h2>Free to read</h2></div><Link href="/news" className="backLink">All news <ChevronRight size={15}/></Link></div>{newsLoading?<div className="empty">Loading personalized headlines…</div>:newsCards.length?<div className="storyGrid">{newsCards.map(s=><a href={s.url} target="_blank" rel="noreferrer" className="storyCard liveStoryCard" key={s.id}>{s.image&&<img src={s.image} alt="" className="storyImage"/>}<div className="storyMeta"><span>{s.source} · {s.league}</span><span>{s.personalized?"FOR YOU":storyAge(s.published)}</span></div><h3>{s.headline}</h3>{s.summary&&<p>{s.summary}</p>}<div className="storyOpen">Read free article <ExternalLink size={13}/></div></a>)}</div>:<div className="storyGrid">{stories.map(s=><article className="storyCard" key={s.id}><div className="storyMeta"><span>{s.source}</span><span>{s.tag}</span></div><h3>{s.headline}</h3><p>{s.summary}</p></article>)}</div>}</section>
 <section className="homeSection"><div className="sectionHead"><div><span className="eyebrow">YOUR LEAGUES</span><h2>Everything you follow</h2></div></div><div className="leagueGrid">{defaultLeaguePrefs.filter(l=>l.coverage!=="off").map(l=><Link className="leagueCard" href={`/league/${l.id}`} key={l.id}><Trophy/><div><strong>{l.name}</strong><small>{l.coverage==="full"?"Full coverage":"Major stories"}</small></div><ChevronRight/></Link>)}</div></section>
 <nav className="bottomNav" aria-label="Primary navigation"><Link href="/"><HomeIcon/><span>Home</span></Link><Link href="/scores"><Trophy/><span>Scores</span></Link><Link href="/search"><Search/><span>Search</span></Link><Link href="/news"><Newspaper/><span>News</span></Link></nav></main>;
}

function TeamBadge({src,label,small=false}:{src:string;label:string;small?:boolean}){const [failed,setFailed]=useState(false);if(failed)return <div className={small?"gameBadge teamBadgeFallback":"teamLogo teamBadgeFallback"}>{label}</div>;return <img src={src} alt="" className={small?"gameBadge":"teamLogoImage"} onError={()=>setFailed(true)}/>}
