"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Search,Settings2,ChevronRight,CalendarDays,Newspaper,Trophy,Home as HomeIcon} from "lucide-react";
import {defaultFavoriteTeamIds,defaultLeaguePrefs,defaultNewsSources,events,stories,teamCatalog} from "@/data/demo";
const KEY="homefield-preferences-v1";
export default function HomeField(){
 const [favoriteIds,setFavoriteIds]=useState(defaultFavoriteTeamIds);const [settings,setSettings]=useState(false);
 useEffect(()=>{try{const r=localStorage.getItem(KEY);if(r)setFavoriteIds(JSON.parse(r).favoriteTeamIds||defaultFavoriteTeamIds)}catch{}},[]);
 const teams=useMemo(()=>favoriteIds.map(id=>teamCatalog.find(t=>t.id===id)).filter(Boolean) as typeof teamCatalog,[favoriteIds]);
 const toggle=(id:string)=>{const next=favoriteIds.includes(id)?favoriteIds.filter(x=>x!==id):[...favoriteIds,id];setFavoriteIds(next);try{const existing=JSON.parse(localStorage.getItem(KEY)||"{}");localStorage.setItem(KEY,JSON.stringify({...existing,favoriteTeamIds:next,leagues:existing.leagues||defaultLeaguePrefs,sources:existing.sources||defaultNewsSources}))}catch{localStorage.setItem(KEY,JSON.stringify({favoriteTeamIds:next,leagues:defaultLeaguePrefs,sources:defaultNewsSources}))}};
 return <main className="homeShell"><header className="homeHeader"><div><div className="brand">HOMEFIELD</div><small>YOUR TEAMS. FIRST.</small></div><div className="headerActions"><Link href="/search" className="iconBtn" aria-label="Search HomeField"><Search size={19}/></Link><button className="iconBtn" aria-label="Personalize HomeField" onClick={()=>setSettings(!settings)}><Settings2 size={19}/></button></div></header>
 {settings&&<section className="settingsPanel"><div className="sectionHead"><div><span className="eyebrow">PERSONALIZE</span><h2>Favorite teams</h2></div></div><div className="settingsTeams">{teamCatalog.map(t=><button key={t.id} className={favoriteIds.includes(t.id)?"settingsTeam active":"settingsTeam"} onClick={()=>toggle(t.id)}>{t.short} · {t.name}</button>)}</div><p>News priority: ESPN first, Bleacher Report second. Paid-only articles such as ESPN+ are excluded.</p></section>}
 <section className="heroWelcome"><span className="eyebrow">GOOD EVENING</span><h1>Your sports world,<br/>built around you.</h1><p>Favorite teams first. Followed leagues next. Big stories everywhere else.</p></section>
 <section className="homeSection"><div className="sectionHead"><div><span className="eyebrow">MY TEAMS</span><h2>HomeField</h2></div></div><div className="teamRail">{teams.map(t=><Link href={`/team/${t.id}`} className="teamTile" key={t.id}><div className="teamLogo" style={{background:`linear-gradient(145deg,${t.primary},${t.secondary})`}}>{t.short}</div><strong>{t.name}</strong><small>{t.league}</small></Link>)}</div></section>
 <section className="homeSection"><div className="sectionHead"><div><span className="eyebrow">LIVE & NEXT UP</span><h2>Your games</h2></div></div><div className="gameGrid">{events.map((g,i)=><Link href={`/game/game-${i+1}`} className="gameCard" key={g.teamId}><CalendarDays/><div><strong>{g.title}</strong><small>{g.detail}</small></div><ChevronRight/></Link>)}</div></section>
 <section className="homeSection"><div className="sectionHead"><div><span className="eyebrow">TOP STORIES FOR YOU</span><h2>Free to read</h2></div></div><div className="storyGrid">{stories.map(s=><article className="storyCard" key={s.id}><div className="storyMeta"><span>{s.source}</span><span>{s.tag}</span></div><h3>{s.headline}</h3><p>{s.summary}</p></article>)}</div></section>
 <section className="homeSection"><div className="sectionHead"><div><span className="eyebrow">YOUR LEAGUES</span><h2>Everything you follow</h2></div></div><div className="leagueGrid">{defaultLeaguePrefs.filter(l=>l.coverage!=="off").map(l=><Link className="leagueCard" href={`/league/${l.id}`} key={l.id}><Trophy/><div><strong>{l.name}</strong><small>{l.coverage==="full"?"Full coverage":"Major stories"}</small></div><ChevronRight/></Link>)}</div></section>
 <nav className="bottomNav" aria-label="Primary navigation"><Link href="/"><HomeIcon/><span>Home</span></Link><Link href="/scores"><Trophy/><span>Scores</span></Link><Link href="/search"><Search/><span>Search</span></Link><Link href="/news"><Newspaper/><span>News</span></Link></nav>
 </main>}
