"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,CalendarDays,Newspaper,BarChart3,Users,Flame} from "lucide-react";
import {teamCatalog,demoGames,demoStories} from "@/data/demo";

type LiveTeamData={
  team:null|{id:string;name:string;league?:string;sport?:string;stadium?:string;location?:string;badge?:string;banner?:string;website?:string};
  nextEvent:null|{id:string;name:string;date?:string;time?:string;venue?:string;status?:string};
  players:Array<{id:string;name:string;position?:string;thumb?:string}>;
  source?:string;
};

export default function TeamPageClient({teamId}:{teamId:string}){
 const team=teamCatalog.find(t=>t.id===teamId);const [tab,setTab]=useState("Overview");const [live,setLive]=useState<LiveTeamData|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!team)return;let cancelled=false;setLoading(true);fetch(`/api/sports/team?name=${encodeURIComponent(team.name.replace(/ Football$| Basketball$/,""))}`).then(r=>r.ok?r.json():null).then(data=>{if(!cancelled)setLive(data)}).catch(()=>{}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[team?.name]);
 if(!team)return <main className="pageShell"><Link href="/" className="backLink"><ArrowLeft/>HomeField</Link><h1>Team not found</h1></main>;
 const games=demoGames.filter(g=>g.teamId===team.id);const stories=demoStories.filter(s=>s.teamId===team.id);const stats=team.sport==="Baseball"?[["Runs/Game","4.7"],["AVG",".258"],["OPS",".744"],["ERA","3.82"]]:team.sport==="Hockey"?[["Goals/Game","3.18"],["Power Play","23.4%"],["Penalty Kill","81.2%"],["Shots/Game","30.8"]]:team.sport==="Soccer"?[["Goals/Game","1.82"],["Possession","54.3%"],["Shots/Game","13.8"],["Pass Accuracy","84.6%"]]:[["Points/Game","31.4"],["Efficiency","47.2%"],["Turnover Margin","+6"],["Form","Strong"]];
 const next=live?.nextEvent;
 return <main className="pageShell"><div className="pageTop"><Link href="/" className="backLink"><ArrowLeft size={17}/>HomeField</Link><span>{live?.team?.league||team.league}</span></div><section className="teamHero" style={{background:live?.team?.banner?`linear-gradient(rgba(10,13,17,.55),rgba(10,13,17,.9)),url(${live.team.banner}) center/cover`:`radial-gradient(circle at 85% 15%,${team.primary}88,transparent 36%),linear-gradient(135deg,#171c23,#0c0f13)`}}><div className="bigMark" style={{background:`linear-gradient(145deg,${team.primary},${team.secondary})`}}>{team.short}</div><div><span className="eyebrow">{live?.team?.sport||team.sport}</span><h1>{live?.team?.name||team.name}</h1><p>{live?.team?.location||team.city}{live?.team?.stadium?` · ${live.team.stadium}`:` · ${team.league}`}</p></div></section><nav className="tabs" aria-label={`${team.name} sections`}>{["Overview","News","Rumors","Schedule","Standings","Stats","Roster"].map(x=><button type="button" onClick={()=>setTab(x)} className={tab===x?"active":""} aria-pressed={tab===x} key={x}>{x}</button>)}</nav>
 {tab==="Overview"&&<><Section label="NEXT UP" title="Games"><div className="gameGrid">{next?<div className="gameCard"><CalendarDays/><div><strong>{next.name}</strong><small>{[next.date,next.time,next.venue].filter(Boolean).join(" · ")}</small></div></div>:loading?<Empty text="Loading live schedule…"/>:games.length?games.map(g=><Link href={`/game/${g.id}`} className="gameCard" key={g.id}><CalendarDays/><div><strong>{g.opponent}</strong><small>{g.detail}</small></div></Link>):<Empty text="No upcoming game found."/>}</div></Section><Section label="TEAM SNAPSHOT" title="Key stats"><div className="statGrid">{stats.map(([a,b])=><div className="statCard" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></Section><Section label="LATEST" title="Team news"><Stories stories={stories} color={team.primary}/></Section></>}
 {tab==="News"&&<Section label="NEWS" title={team.name}><Stories stories={stories} color={team.primary}/></Section>}
 {tab==="Rumors"&&<Section label="RUMOR WIRE" title="Movement"><div className="rumorGrid"><Rumor status="Heating Up"/><Rumor status="Worth Watching"/><Rumor status="Buzz"/></div></Section>}
 {tab==="Schedule"&&<Section label="SCHEDULE" title="Games"><div className="gameGrid">{next?<div className="gameCard"><CalendarDays/><div><strong>{next.name}</strong><small>{[next.date,next.time,next.venue].filter(Boolean).join(" · ")}</small></div></div>:games.length?games.map(g=><Link href={`/game/${g.id}`} className="gameCard" key={g.id}><CalendarDays/><div><strong>{g.opponent}</strong><small>{g.detail}</small></div></Link>):<Empty text="No schedule entries are available yet."/>}</div></Section>}
 {tab==="Standings"&&<Section label="STANDINGS" title="Position"><div className="table"><div><b>1</b><span>{team.name}</span><strong>—</strong></div><div><b>2</b><span>League competitor</span><strong>—</strong></div><div><b>3</b><span>League competitor</span><strong>—</strong></div></div></Section>}
 {tab==="Stats"&&<Section label="STATS" title="Team performance"><div className="statGrid">{stats.concat(stats.slice(0,2)).map(([a,b],i)=><div className="statCard" key={i}><BarChart3/><span>{a}</span><strong>{b}</strong></div>)}</div></Section>}
 {tab==="Roster"&&<Section label="ROSTER" title="Players">{loading?<div className="roster"><Users/><p>Loading live roster…</p></div>:live?.players?.length?<div className="storyList">{live.players.map(p=><div className="searchListRow" key={p.id}><Users size={18}/><div><strong>{p.name}</strong><small>{p.position||"Player"}</small></div></div>)}</div>:<div className="roster"><Users/><p>Roster data is not available from the free feed for this team yet.</p></div>}</Section>}
 </main>}
function Section({label,title,children}:{label:string,title:string,children:React.ReactNode}){return <section className="contentSection"><div className="sectionHead"><div><span className="eyebrow">{label}</span><h2>{title}</h2></div></div>{children}</section>}
function Stories({stories,color}:{stories:any[],color:string}){return <div className="storyList">{stories.length?stories.map(s=><article className="storyRow" key={s.id}><div className="storyThumb" style={{background:`linear-gradient(145deg,${color},#171c23)`}}><Newspaper/></div><div><small>{s.source} · {s.time}</small><h3>{s.headline}</h3><p>{s.summary}</p></div></article>):<Empty text="Free-to-read team coverage will populate here."/>}</div>}
function Rumor({status}:{status:string}){return <div className="rumorCard"><span><Flame size={14}/>{status}</span><h3>Trusted-source rumor tracking</h3><p>Credible reporter activity will be grouped and confidence-ranked here.</p><small>Multiple-source verification</small></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
